all:
  hosts:
    orion:
      ansible_host: 192.168.100.20
    orion-nodepi:
      ansible_host: 192.168.100.21
    orion-node02:
      ansible_host: 192.168.100.22
    jellyfin:
      ansible_host: 192.168.100.100
    centreon-prod:
      ansible_host: 192.168.100.7
    adguard:
      ansible_host: 192.168.100.97
    bitwarden:
      ansible_host: 192.168.100.99
    komodo:
      ansible_host: 192.168.100.101
    node01:
      ansible_host: 192.168.100.98
    node02:
      ansible_host: 192.168.100.126

physical:
  hosts:
    orion:
    orion-nodepi:
    orion-node02:

virtual:
  hosts:
    adguard:
    bitwarden:
    komodo:
    node01:
    node02:

media:
  hosts:
    jellyfin:

monitoring:
  hosts:
    centreon-prod:
