all:
  hosts:
    orion:
      ansible_host: 192.168.100.20
    orion-nodepi:
      ansible_host: 192.168.100.21
    jellyfin:
      ansible_host: 192.168.100.100
    orion-node02:
      ansible_host: 192.168.100.122
    adguard:
      ansible_host: 192.168.100.97
    node01:
      ansible_host: 192.168.100.98
    bitwarden:
      ansible_host: 192.168.100.99
    immich:
      ansible_host: 192.168.100.104
    immich-ml:
      ansible_host: 192.168.100.103
      ansible_user: root

  children:
    physical:
      hosts:
        orion:
        orion-nodepi:
        orion-node02:
    media:
      hosts:
        jellyfin:
    monitoring:
      hosts:
        centreon-prod:
