all:
  hosts:
    centreon-prod:
      ansible_host: 192.168.100.7
    orion:
      ansible_host: 192.168.100.20
    orion-nodepi:
      ansible_host: 192.168.100.21
    jellyfin:
      ansible_host: 192.168.100.100
    docker-host:
      ansible_host: 192.168.100.101
    orion-node02:
      ansible_host: 192.168.100.122
    node02:
      ansible_host: 192.168.100.126
    adguard:
      ansible_host: 192.168.100.97
    node01:
      ansible_host: 192.168.100.98
    bitwarden:
      ansible_host: 192.168.100.99
    jellyfin-v3:
      ansible_host: 192.168.100.103

  children:
    physical:
      hosts:
        orion:
        orion-nodepi:
        orion-node02:
    virtual:
      hosts:
        adguard:
        bitwarden:
        docker-host:
        node01:
        node02:
        jellyfin:
        jellyfin-v3:
    debian:
      hosts:
        orion:
        orion-nodepi:
        orion-node02:
        node01:
        node02:
        bitwarden:
        adguard:
        jellyfin:
        docker-host:
    media:
      hosts:
        jellyfin:
    monitoring:
      hosts:
        centreon-prod: