- name: SYSTEM UPDATE - DEBIAN
  hosts: all
  become: true
  vars:
    free_space_gb: "1"

  tasks:
    - name: Test DNS resolution for twm.ch
      ansible.builtin.command: nslookup proxy.core-forge.fyi
      changed_when: false
      register: dns_test

    - name: Display DNS test results
      ansible.builtin.debug:
        var: dns_test.stdout_lines

    - name: Ensure we have enough disk space
      ansible.builtin.assert:
        that:
          - (ansible_mounts | selectattr('mount', 'equalto', item) | map(attribute='size_available') | first | default(0) / 1024 / 1024 / 1024) | float > (free_space_gb | float)
        fail_msg: "Insufficient space on {{ item }}."
        success_msg: "Disk space check passed for {{ item }}."
      loop:
        - /

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Reboot the server after patching
      ansible.builtin.reboot:
        msg: "WARNING! REBOOT WAS INITIATED BY ANSIBLE DUE SYSTEM PATCHING. THE SYSTEM WILL REBOOT IN 1 MIN"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 60
        post_reboot_delay: 30