---
- name: Allow cloudinit root user
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: "^disable_root: true"
    line: "disable_root: false"
  failed_when: false

- name: Limit journalctl log size
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^SystemMaxUse="
    line: "SystemMaxUse={{ log_size }}"
  failed_when: false

- name: Copy tweaked sysctl configuration
  ansible.builtin.template:
    src: 98-sysctl-tweaks.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: "0644"

- name: Restart journalctl service
  ansible.builtin.systemd_service:
    state: restarted
    name: systemd-journald
  failed_when: false
