---
- name: Homelab
  hosts: all

  roles:
    # CORE:
    - role: ssh
      tags: ssh
    - role: system_tweaks
      tags: system_tweaks
    - role: bashrc
      tags: bashrc
    - role: swapfile
      tags: swapfile
    - role: update_motd
      tags: update_motd
    - role: reboot
      tags: reboot
    - role: centreon_monitoring
      tags: centreon_monitoring
    # OPTIONAL:
    - role: docker
      tags: never, docker
    - role: backup_proxmox
      tags: never, backup_proxmox
    - role: syncthing
      tags: syncthing
    - role: minimal_packages
      tags: never,minimal_packages
