name: adguard_dns_update

on:
  push:
    branches:
      - main

jobs:
  update_adguard_dns:
    name: pull image
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:latest
      volumes:
        - /var/local/terraform-state:/opt/terraform-state:rw

    env:
      TF_DIR: "terraform/prod/services/AdGuard/adguard-dns"
      TF_VAR_adguard_admin_password: ${{ secrets.ADGUARD_ADMIN_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: |
          cd ${{ env.TF_DIR }}
          terraform init -input=false

      # Optional: Keeps your drift detection safely working inside the same execution block
      - name: Terraform Plan
        run: |
          cd ${{ env.TF_DIR }}
          terraform plan -refresh-only -detailed-exitcode || DRIFT_EXIT_CODE=$?
          terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        run: |
          cd ${{ env.TF_DIR }}
          terraform apply -input=false tfplan