name: adguard_dns_update

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/prod/services/AdGuard/adguard-dns/**'

jobs:
  update_adguard_dns:
    name: update_dns_records
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:latest
      volumes:
        - /var/local/terraform-state:/opt/terraform-state:rw

    env:
      TF_DIR: "terraform/prod/services/AdGuard/adguard-dns"
      TF_VAR_adguard_admin_password: ${{ secrets.ADGUARD_ADMIN_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Terraform Init
        run: |
          cd ${{ env.TF_DIR }}
          terraform init -input=false

      - name: Terraform Run
        run: |
          cd ${{ env.TF_DIR }}
          terraform plan -out=tfplan -input=false
          terraform apply -input=false tfplan